-- SUPABASE SCHEMA FOR BIRTHDAY INVITE
-- Run in Supabase SQL Editor.
-- IMPORTANT: This stores only data the recipient actively provides/shares.
-- Do not expose a service-role key in browser code.

create table if not exists public.invite_events (
  id bigint generated by default as identity primary key,
  invite_id text not null,
  session_id text not null,
  type text not null,
  data jsonb not null default '{}'::jsonb,
  timestamp timestamptz not null default now()
);

create table if not exists public.invite_responses (
  id bigint generated by default as identity primary key,
  invite_id text not null,
  session_id text not null,
  place text not null,
  date date not null,
  time time not null,
  address text,
  location jsonb,
  submitted_at timestamptz not null default now()
);

alter table public.invite_events enable row level security;
alter table public.invite_responses enable row level security;

-- Recipient needs INSERT only:
create policy "invite events insert"
on public.invite_events for insert
to anon
with check (true);

create policy "invite responses insert"
on public.invite_responses for insert
to anon
with check (true);

-- Dashboard should NOT use the anon key to read all responses.
-- Read data securely through an authenticated/admin dashboard or server.
